### ISSUE TITLE
mkdir is hanging

### ISSUE THREAD

**Issue by ninkisa** [ipfs/go-mfs#79]
Hello,

I'm using MFS via the go-ipfs-api and I'm running multiple goroutines against ipfs
It looks that mkdir dir command is hanging 
I'm attaching goroutine dump
[ipfs.stacks.txt](https://github.com/ipfs/go-mfs/files/3525001/ipfs.stacks.txt)

goroutine 4205 [semacquire, 113 minutes]:
sync.runtime_SemacquireMutex(0xc000b04cbc, 0x0)
	/usr/lib/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc000b04cb8)
	/usr/lib/go/src/sync/mutex.go:134 +0x109
github.com/ipfs/go-mfs.(*Directory).Child(0xc000b04c80, 0xc0021b6d72, 0x6, 0x0, 0x0, 0x0, 0x0)
	pkg/mod/github.com/ipfs/go-mfs@v0.0.7/dir.go:200 +0x47
github.com/ipfs/go-mfs.Mkdir(0xc001269290, 0xc0021b6d60, 0x1f, 0x100, 0x0, 0x0, 0x2, 0xc000305b20)
	pkg/mod/github.com/ipfs/go-mfs@v0.0.7/ops.go:154 +0x177
github.com/ipfs/go-ipfs/core/commands.glob..func71(0xc001ef13b0, 0x1ac57e0, 0xc0001d7300, 0x16ccf00, 0xc0006c2de0, 0x0, 0x0)
	pkg/mod/github.com/ipfs/go-ipfs@v0.4.22/core/commands/files.go:847 +0x1d8
github.com/ipfs/go-ipfs-cmds.(*Command).call(0x23b1fe0, 0xc001ef13b0, 0x1ac57e0, 0xc0001d7300, 0x16ccf00, 0xc0006c2de0, 0xd0000000149974f, 0xc0014975e0)

Can you help with this?

Thank you in advance

**Comment by Stebalien** [comment]
The issue is that we're trying to _find_ a block on the network while holding that lock. Specifically, `Child` takes the lock and then eventually calls `childFromDag`. This may need to fetch something from the network.

The correct solution is to do whatever we need to do with the lock, unlock, fetch the next block from the dag, relock.
